version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    mem_limit: 500m
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=mongo
    #   - MONGO_INITDB_ROOT_PASSWORD=mongo
    #   - MONGO_INITDB_DATABASE=root-db
    volumes:
      # seeding scripts
      # - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # named volumes
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb

  app:
    build: .
    mem_limit: 500m
    depends_on:
      - db
