name: Check code

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install flake8 and plugins
        run: pip install flake8 flake8-black flake8-isort

      - name: Lint with flake8
        run: flake8 --show-source --statistics --count

  check-type:
    name: Run type checker
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mypy
          pip install -r requirements.txt

      - name: Check type with mypy
        run: mypy --package=app

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pytest mongomock
          pip install -r requirements.txt

      - name: Run functional tests with pytest
        run: pytest
